name: actions-slack
description: Notify via slack in GitHub Actions workflow
author: innocarpe
inputs:
  status:
    description: "The status of the job, usually: jobs.<job_id>.status"
    required: true
  success_text:
    description: Slack message when succeeded.
    default: "Succeeded 🚀"
  failure_text:
    description: Slack message when failed.
    default: "Failed 😱"
  cancelled_text:
    description: Slack message when cancelled.
    default: "Cancelled ⚠️"
runs:
  using: 'node16'
  main: lib/main.js
branding:
  icon: bell
  color: black
